<!-- Pension Report Template -->
<div class="report-container">
    <div class="report-header">
        <div class="logo-container">
            <img src="{{ asset('images/OSCA.png') }}" alt="Logo" class="report-logo">
        </div>
        <div class="header-text">
            <h1>Senior Citizens with Pension</h1>
            <h3>Report Date: {{ $date }}</h3>
        </div>
    </div>

    <div class="report-summary">
        <p><strong>Total Seniors with Pension:</strong> {{ $total }}</p>
    </div>

    <div class="report-table-container">
        <table class="report-table">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>OSCA ID</th>
                    <th>Full Name</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Barangay</th>
                </tr>
            </thead>
            <tbody>
                @foreach($seniors as $index => $senior)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $senior->osca_id }}</td>
                    <td>{{ $senior->first_name }} {{ $senior->middle_name ? substr($senior->middle_name, 0, 1) . '.' : '' }} {{ $senior->last_name }}</td>
                    <td>{{ \Carbon\Carbon::parse($senior->date_of_birth)->age }}</td>
                    <td>{{ $senior->sex }}</td>
                    <td>{{ $senior->barangay }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="report-footer">
        <p>Generated by ELDERA IMS on {{ $date }}</p>
    </div>
</div>