name: eldera
description: A comprehensive health monitoring mobile application for elderly care.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  intl: ^0.19.0
  shared_preferences: ^2.2.2

  flutter_tts: ^3.8.5
  google_fonts: ^6.1.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  image_picker: ^1.0.4
  flutter_secure_storage: ^9.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  device_calendar: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
